line-length = 88

[lint]
select = [
    "E4",   # Import errors
    "E7",   # Statement errors
    "E9",   # Runtime errors
    "F",    # Pyflakes
	"I",    # Import
    "B",    # flake8-bugbear
	"W",    # whitespace
]

ignore = [
    "E501", # Line too long (handled by formatter)
]

[format]
quote-style = "single"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = "dynamic"
